project:
  type: website
  output-dir: ../docs

website:
  title: "607 Sensory Coding"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: 2dcnn.qmd
        text: 2DCNN
      - href: 3dcnn.qmd
        text: 3DCNN
      - href: bigrf.qmd
        text: bigRF
    tools:
      - icon: github
        href: https://github.com/nghess/607-sensory-coding

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



